name: Release jobs

on:
  release:
    types: [published]

jobs:
  new_release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.2.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Npm install
      run: npm install
    - name: Write env
      id: write_file
      uses: timheuer/base64-to-file@v1.1
      with:
        fileName: '.env'
        encodedString: ${{ secrets.ENV_VARIABLES }}
    - name: Move env
      run: mv ${{steps.write_file.outputs.filePath}} ./
    - name: Build
      run: npm run build
    - name: Archive Production Artifact
      uses: actions/upload-artifact@main
      with:
        name: dist
        path: dist
    - run: curl -sL https://firebase.tools | bash
    - name: Download Artifact
      uses: actions/download-artifact@main
      with:
        name: dist
        path: 
    - name: Deploy to Firebase Firestore Rules
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only firestore:rules, hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    
